[[su2]]
virtual_mps = [{sectors = [1], dims = [1]}, {sectors = [2], dims = [1]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1], dims = [1]}, {sectors = [2], dims = [1]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3], dims = [1, 1]}, {sectors = [2], dims = [2]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3], dims = [1, 1]}, {sectors = [2], dims = [2]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3], dims = [2, 2]}, {sectors = [2, 4], dims = [3, 1]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3], dims = [2, 3]}, {sectors = [2, 4], dims = [3, 2]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5], dims = [3, 4, 1]}, {sectors = [2, 4], dims = [4, 3]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5], dims = [4, 5, 2]}, {sectors = [2, 4], dims = [6, 4]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5], dims = [5, 8, 3]}, {sectors = [2, 4, 6], dims = [8, 6, 1]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5], dims = [7, 12, 5]}, {sectors = [2, 4, 6], dims = [13, 9, 1]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5], dims = [11, 17, 7]}, {sectors = [2, 4, 6], dims = [17, 12, 3]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5, 7], dims = [15, 24, 11, 1]}, {sectors = [2, 4, 6], dims = [22, 18, 5]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5, 7], dims = [19, 32, 18, 2]}, {sectors = [2, 4, 6], dims = [31, 29, 7]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5, 7], dims = [26, 49, 25, 4]}, {sectors = [2, 4, 6, 8], dims = [46, 38, 12, 1]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5, 7], dims = [39, 68, 38, 7]}, {sectors = [2, 4, 6, 8], dims = [59, 57, 20, 2]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5, 7], dims = [51, 96, 58, 12]}, {sectors = [2, 4, 6, 8], dims = [88, 83, 30, 3]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5, 7, 9], dims = [75, 136, 83, 21, 1]}, {sectors = [2, 4, 6, 8], dims = [121, 119, 48, 6]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5, 7, 9], dims = [103, 198, 123, 33, 2]}, {sectors = [2, 4, 6, 8], dims = [177, 173, 71, 11]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5, 7, 9], dims = [145, 277, 184, 54, 4]}, {sectors = [2, 4, 6, 8], dims = [241, 251, 110, 20]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5, 7, 9], dims = [203, 399, 265, 87, 9]}, {sectors = [2, 4, 6, 8, 10], dims = [342, 357, 172, 33, 1]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5, 7, 9], dims = [280, 566, 397, 135, 16]}, {sectors = [2, 4, 6, 8, 10], dims = [488, 516, 256, 56, 3]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5, 7, 9, 11], dims = [394, 803, 586, 210, 30, 1]}, {sectors = [2, 4, 6, 8, 10], dims = [683, 746, 384, 95, 7]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5, 7, 9, 11], dims = [552, 1137, 860, 326, 56, 2]}, {sectors = [2, 4, 6, 8, 10], dims = [965, 1080, 573, 154, 15]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]
[[su2]]
virtual_mps = [{sectors = [1, 3, 5, 7, 9, 11], dims = [785, 1627, 1259, 499, 97, 5]}, {sectors = [2, 4, 6, 8, 10], dims = [1363, 1555, 862, 247, 29]}]
physical = [{sectors = [2], dims = [1]}, {sectors = [2], dims = [1]}]
virtual_mpo = [{sectors = [1, 3], dims = [2, 1]}, {sectors = [1, 3], dims = [2, 1]}]

[[trivial]]
virtual_mps = [1, 2]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [1, 2]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [4, 4]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [4, 4]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [8, 10]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [11, 14]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [20, 20]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [29, 28]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [44, 46]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [68, 68]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [97, 100]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [149, 146]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [219, 220]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [326, 324]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [482, 482]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [713, 712]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [1054, 1054]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [1561, 1560]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [2310, 2306]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [3415, 3418]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [5052, 5054]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [7484, 7484]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [11071, 11070]
physical = [2, 2]
virtual_mpo = [5, 5]
[[trivial]]
virtual_mps = [16382, 16384]
physical = [2, 2]
virtual_mpo = [5, 5]

[[u1]]
virtual_mps = [{sectors = [0], dims = [1]}, {sectors = [1, -1], dims = [1, 1]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0], dims = [1]}, {sectors = [1, -1], dims = [1, 1]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2], dims = [2, 1, 1]}, {sectors = [1, -1], dims = [2, 2]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2], dims = [2, 1, 1]}, {sectors = [1, -1], dims = [2, 2]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2], dims = [4, 2, 2]}, {sectors = [1, -1, 3, -3], dims = [4, 4, 1, 1]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2], dims = [5, 3, 3]}, {sectors = [1, -1, 3, -3], dims = [5, 5, 2, 2]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4], dims = [8, 5, 5, 1, 1]}, {sectors = [1, -1, 3, -3], dims = [7, 7, 3, 3]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4], dims = [11, 7, 7, 2, 2]}, {sectors = [1, -1, 3, -3], dims = [10, 10, 4, 4]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4], dims = [16, 11, 11, 3, 3]}, {sectors = [1, -1, 3, -3, 5, -5], dims = [15, 15, 7, 7, 1, 1]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4], dims = [24, 17, 17, 5, 5]}, {sectors = [1, -1, 3, -3, 5, -5], dims = [23, 23, 10, 10, 1, 1]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4], dims = [35, 24, 24, 7, 7]}, {sectors = [1, -1, 3, -3, 5, -5], dims = [32, 32, 15, 15, 3, 3]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4, 6, -6], dims = [51, 36, 36, 12, 12, 1, 1]}, {sectors = [1, -1, 3, -3, 5, -5], dims = [45, 45, 23, 23, 5, 5]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4, 6, -6], dims = [71, 52, 52, 20, 20, 2, 2]}, {sectors = [1, -1, 3, -3, 5, -5], dims = [67, 67, 36, 36, 7, 7]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4, 6, -6], dims = [104, 78, 78, 29, 29, 4, 4]}, {sectors = [1, -1, 3, -3, 5, -5, 7, -7], dims = [97, 97, 51, 51, 13, 13, 1, 1]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4, 6, -6], dims = [152, 113, 113, 45, 45, 7, 7]}, {sectors = [1, -1, 3, -3, 5, -5, 7, -7], dims = [138, 138, 79, 79, 22, 22, 2, 2]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4, 6, -6], dims = [217, 166, 166, 70, 70, 12, 12]}, {sectors = [1, -1, 3, -3, 5, -5, 7, -7], dims = [204, 204, 116, 116, 33, 33, 3, 3]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4, 6, -6, 8, -8], dims = [316, 241, 241, 105, 105, 22, 22, 1, 1]}, {sectors = [1, -1, 3, -3, 5, -5, 7, -7], dims = [294, 294, 173, 173, 54, 54, 6, 6]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4, 6, -6, 8, -8], dims = [459, 356, 356, 158, 158, 35, 35, 2, 2]}, {sectors = [1, -1, 3, -3, 5, -5, 7, -7], dims = [432, 432, 255, 255, 82, 82, 11, 11]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4, 6, -6, 8, -8], dims = [664, 519, 519, 242, 242, 58, 58, 4, 4]}, {sectors = [1, -1, 3, -3, 5, -5, 7, -7], dims = [622, 622, 381, 381, 130, 130, 20, 20]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4, 6, -6, 8, -8], dims = [963, 760, 760, 361, 361, 96, 96, 9, 9]}, {sectors = [1, -1, 3, -3, 5, -5, 7, -7, 9, -9], dims = [905, 905, 563, 563, 206, 206, 34, 34, 1, 1]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4, 6, -6, 8, -8], dims = [1394, 1114, 1114, 548, 548, 151, 151, 16, 16]}, {sectors = [1, -1, 3, -3, 5, -5, 7, -7, 9, -9], dims = [1319, 1319, 831, 831, 315, 315, 59, 59, 3, 3]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4, 6, -6, 8, -8, 10, -10], dims = [2024, 1630, 1630, 827, 827, 241, 241, 31, 31, 1, 1]}, {sectors = [1, -1, 3, -3, 5, -5, 7, -7, 9, -9], dims = [1915, 1915, 1232, 1232, 486, 486, 102, 102, 7, 7]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4, 6, -6, 8, -8, 10, -10], dims = [2933, 2381, 2381, 1244, 1244, 384, 384, 58, 58, 2, 2]}, {sectors = [1, -1, 3, -3, 5, -5, 7, -7, 9, -9], dims = [2787, 2787, 1822, 1822, 742, 742, 169, 169, 15, 15]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
[[u1]]
virtual_mps = [{sectors = [0, 2, -2, 4, -4, 6, -6, 8, -8, 10, -10], dims = [4272, 3487, 3487, 1860, 1860, 601, 601, 102, 102, 5, 5]}, {sectors = [1, -1, 3, -3, 5, -5, 7, -7, 9, -9], dims = [4056, 4056, 2693, 2693, 1138, 1138, 276, 276, 29, 29]}]
physical = [{sectors = [1, -1], dims = [1, 1]}, {sectors = [1, -1], dims = [1, 1]}]
virtual_mpo = [{sectors = [0, 2, -2], dims = [3, 1, 1]}, {sectors = [0, 2, -2], dims = [3, 1, 1]}]
